name: "FastApi"

services:
  postgresql:
    image: pgvector/pgvector:pg16
    container_name: postgresql
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: Database
#    volumes:
#      - ./postgres_data:/var/lib/postgresql/data
    networks:
      - app
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d Database" ]
      interval: 30s
      timeout: 10s
      retries: 3

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: always
    env_file:
      - .env
    command: >
      redis-server
      --requirepass "${REDIS_PASSWORD}"
      --appendonly yes
    networks:
      - app
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 3

  neo4j:
    image: neo4j:5
    container_name: neo4j
    restart: always
    environment:
      NEO4J_AUTH: neo4j/${NEO4J_PASSWORD}
      NEO4J_PLUGINS: '["apoc"]'
    ports:
      - "7474:7474"
      - "7687:7687"
    networks:
      - app
    healthcheck:
      test: [ "CMD", "cypher-shell", "-u", "${NEO4J_USER}", "-p", "${NEO4J_PASSWORD}", "RETURN 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  main:
    build: .
    container_name: fastapi
    restart: always
    ports:
      - 8000:8000
    networks:
      - app
    volumes:
      - ./.cache/huggingface:/root/.cache/huggingface
    depends_on:
      postgresql:
        condition: service_healthy
      redis:
        condition: service_healthy

volumes:
  hf_cache:
#  postgres_data:

networks:
  app:
    driver: bridge
